POST http://localhost:3000/short-link
Content-Type: application/json

{
    "longUrl": "https://guru-learner.com"
}
###

GET http://localhost:3000/short-link/otVcuw3


### ALL SHORT LINKS

GET http://localhost:3000/short-link

### DELETE A LINK 

DELETE http://localhost:3000/short-link/kZUoeCcsdf