POST http://localhost:3000/short-link
Content-Type: application/json

{
    "longUrl": "https://guru-learner.ci"
}
###

GET http://localhost:3000/short-link/9Q3mFQJ


### ALL SHORT LINKS

GET http://localhost:3000/short-link

### DELETE A LINK 

DELETE http://localhost:3000/short-link/kZUoeCcsdfq